name: Ruff
on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install poetry
                poetry install
            - name: Ruff Ruff
              run: |
                ruff --output-format=github